name: destor_app
description: "Gamified Learning App for Design Students"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # Navigation
  go_router: ^12.1.3

  # Local Storage
  shared_preferences: ^2.2.2

  # UI Components
  google_fonts: ^6.1.0

  # Icons
  cupertino_icons: ^1.0.2

  # Image handling
  cached_network_image: ^3.3.0

  # JSON handling
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/font.ttf
